news_curation/post/models.py
"""Post models"""

from datetime import datetime, timezone
from news_curation.extensions import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now(timezone.utc))
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    #use the author attribute to access post author details

    comments = db.relationship('Comment', backref='post', lazy=True, cascade = "all,delete")

    def __repr__(self):
        return f"Post('{self.title}', '{self.created_at}')"

news_curation/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired, ValidationError
from news_curation.classifier.utils import predict

class PostForm(FlaskForm):
	title = StringField('Title', 
		validators=[DataRequired()], 
		render_kw={"placeholder": "Title"})
	content = TextAreaField('Content', 
		validators=[DataRequired()], 
		render_kw={"placeholder": "Tell us your thoughts..."})
	topics = SelectField('Topics', coerce=int, validators=[DataRequired()]) #dropdown options are defined in routes.py

	add_topic = SubmitField('Add Tag')
	submit = SubmitField('Post')

	# validate content using model

	def validate_content(self, content):
		if predict(content.data):
			raise ValidationError("Content is detected as fake.")

news_curation/post/__init__.py
from flask import Blueprint

bp = Blueprint("post", __name__)

from news_curation.post import routes, models

news_curation/post/routes.py
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import login_required, current_user

from news_curation.extensions import db

from news_curation.post import bp
from news_curation.post.models import Post

from news_curation.comment.forms import CommentForm

from news_curation.post.forms import PostForm
from news_curation.post.models import Post

from news_curation.topic.models import Topic, topics


@bp.route("/")
def home():
    return "post home"

# <<<<<<< HEAD
# @bp.route("/<int:post_id>", methods=["POST","GET"])
# @login_required
# def read(post_id):
#     post = Post.query.get_or_404(post_id)

#     form = CommentForm()

#     # if form.validate_on_submit():
#     #     pass

#     return post.content
# =======

tags = []
@bp.route("/create", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    form.topics.choices = [(g.id, g.topic) for g in Topic.query.order_by('topic')] #choices for the topic dropdown.
    dropdown_error = None
    if request.method == 'POST':
        if form.submit.data: #when user clicks the 'Post' button
            if not tags: #if there were no tags added
                dropdown_error = "Tags cannot be empty! Please add at least one."
                return render_template('post/manage_post.html', form=form, legend='New Post', 
                                        tags=tags, dropdown_error=dropdown_error)
            elif form.validate_on_submit():
                post = Post(title=form.title.data, content=form.content.data, author=current_user)
                db.session.add(post) #adds new post to database
                
                for tag in tags: #add selected tags to the post in the database
                    post_tag = Topic.query.filter_by(topic=tag).first()
                    post.topic.append(post_tag)

                db.session.commit()
                del tags[0:] #delete all content of the 'tags' list
                flash('Post has been created!', 'success')
                return redirect(url_for('user.home'))

        elif form.add_topic.data: #when user clicks the 'add topic' button
            #append name of selected choice to a list
            
            topic_name = dict(form.topics.choices).get(form.topics.data)
            try:
                tags.index(topic_name) #checks if a tag is already in the 'tags' list
            except:
                tags.append(topic_name) #appends the selected tag to 'tags' if it is not yet in the list
            else:
                dropdown_error = "This tag has already been added!"
            return render_template('post/manage_post.html', form=form, legend='New Post', 
                                        tags=tags, dropdown_error=dropdown_error)

        elif request.form['tag_to_remove']: #when one of the added tags is clicked (this will remove that tag)
            tag_name = request.form.get('tag_to_remove')
            tags.remove(tag_name)
            return render_template('post/manage_post.html', form=form, legend='New Post', tags=tags)
    
    del tags[0:]
    return render_template('post/manage_post.html', form=form, legend='New Post')


#viewing a single post
@bp.route("/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post/post.html', post=post)

tags_to_remove = []
@bp.route("<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    # tags = []
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: #if logged-in user is not the author of post, abort
        abort(403)

    form = PostForm()
    form.topics.choices = [(g.id, g.topic) for g in Topic.query.order_by('topic')] #choices for the topic dropdown.
    dropdown_error = None

    if request.method == 'POST':
        if form.submit.data and form.validate_on_submit(): #updates the post
            if not tags: #if there were no tags added
                dropdown_error = "Tags cannot be empty! Please add at least one."
                return render_template('post/manage_post.html', form=form, legend='Update Post', 
                                        tags=tags, dropdown_error=dropdown_error)
            post.title = form.title.data
            post.content = form.content.data
            for tag in tags_to_remove:
                tag_row = Topic.query.filter_by(topic=tag).first() #gets the row of selected tag in Topic table
                if tag_row in post.topic:
                    post.topic.remove(tag_row)

            for tag in tags: #add selected tags to the post in the database
                tag_row = Topic.query.filter_by(topic=tag).first() #gets the row of selected tag in Topic table
                #if selected tag is not yet associated to the post
                if tag_row not in post.topic: #prevents duplicate rows in topics table
                    post.topic.append(tag_row)
            
            db.session.commit()
            del tags[0:] #delete all content of the 'tags' list
            del tags_to_remove[0:]
            flash('Post has been updated!', 'success')
            return redirect(url_for('post.post', post_id=post.id))

        elif form.add_topic.data: #when user clicks the 'add topic' button
            #append name of selected choice to a list
            topic_name = dict(form.topics.choices).get(form.topics.data)
            try:
                tags.index(topic_name) #checks if a tag is already in the 'tags' list
            except:
                tags.append(topic_name) #appends the selected tag to 'tags' if it is not yet in the list
            else:
                dropdown_error = "This tag has already been added!"
                return render_template('post/manage_post.html', form=form, legend='Update Post',
                                        tags=tags, dropdown_error=dropdown_error)

        elif request.form['tag_to_remove']: #when one of the added tags is clicked (this will remove that tag)
            tag_name = request.form.get('tag_to_remove')
            tags_to_remove.append(tag_name)
            tags.remove(tag_name)

    elif request.method == 'GET': #displays the data of the post when page is opened
        form.title.data = post.title
        form.content.data = post.content
        del tags[0:]
        for topic in post.topic:   
            tags.append(topic.topic)

    return render_template('post/manage_post.html', title='Update Post', form=form, legend='Update Post', tags=tags)


@bp.route("/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted!', 'success')
    return redirect(url_for('user.profile'))


# Saving post
@bp.route("/<int:post_id>/save")
@login_required
def save_post(post_id):
	home = request.args.get('home')
	post = Post.query.get_or_404(post_id)

	if current_user in post.saved_by:	# if user has already saved the post
	    flash('Post is already in Saved Posts', 'info')
	else:
	    post.saved_by.append(current_user)
	    db.session.commit()
	    flash('Post has been saved!', 'success')

	if home == 'True': #return to homepage if saved from there
		return redirect(url_for('user.home', _anchor=post_id))
	elif home == 'Profile':
		return redirect(url_for('user.profile', _anchor=post_id))
	elif home == 'Popular':
		return redirect(url_for('user.popular', _anchor=post_id))
	else:
		return redirect(url_for('post.post', post_id=post_id))


# Removing saved post
@bp.route("/<int:post_id>/remove_saved")
@login_required
def remove_saved(post_id):
	home = request.args.get('home')

	post = Post.query.get_or_404(post_id)
	post.saved_by.remove(current_user)
	db.session.commit()
	flash('Post removed from Saved Posts', 'info')

	if home == 'True': #return to homepage if saved from there
		return redirect(url_for('user.home', _anchor=post_id))
	elif home == 'Saves':
		return redirect(url_for('user.saved_posts'))
	elif home == 'Profile':
		return redirect(url_for('user.profile', _anchor=post_id))
	elif home == 'Popular':
		return redirect(url_for('user.popular', _anchor=post_id))
	else:
		return redirect(url_for('post.post', post_id=post_id))


#Liking post
@bp.route("/<int:post_id>/like")
@login_required
def like_post(post_id):
	home = request.args.get('home')

	post = Post.query.get_or_404(post_id)
	# post.likes += 1
	# db.session.commit()

	if current_user not in post.liker:
		post.liker.append(current_user)
		if current_user in post.disliker: #if current user dislikes the post, remove dislike
			post.disliker.remove(current_user)
	else:
		post.liker.remove(current_user)
	
	db.session.commit()

	if home == 'True': #return to homepage if liked from there
		return redirect(url_for('user.home', _anchor=post_id))
	elif home == 'Saves':
		return redirect(url_for('user.saved_posts', _anchor=post_id))
	elif home == 'Profile':
		return redirect(url_for('user.profile', _anchor=post_id))
	elif home == 'Popular':
		return redirect(url_for('user.popular', _anchor=post_id))
	else:
		return redirect(url_for('post.post', post_id=post_id))

#Disliking post
@bp.route("/<int:post_id>/dislike")
@login_required
def dislike_post(post_id):
	home = request.args.get('home')

	post = Post.query.get_or_404(post_id)

	if current_user not in post.disliker: #if user is first time disliker, add to db
		post.disliker.append(current_user)
		if current_user in post.liker: #if current user likes the post, remove like
			post.liker.remove(current_user)
	else:
		post.disliker.remove(current_user)
	
	db.session.commit()

	if home == 'True': #return to homepage if disliked from there
		return redirect(url_for('user.home', _anchor=post_id))
	elif home == 'Saves':
		return redirect(url_for('user.saved_posts', _anchor=post_id))
	elif home == 'Profile':

news_curation/templates/post/manage_post.html
{% extends "layout.html" %}

{% block style %}
	<link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}Home{% endblock %}

{% block header_class %}
<!-- classname for small header -->
	header
{% endblock %}

{% block content %}
	<div class="content-container mx-auto p-5 shadow-sm">

    <!--create post-->
    <div class="media px-5 py-2 my-4 rounded shadow-sm">
      <!--header-->
      <div>
        <h4 class="text-center w-100">{{ legend }}</h4>
      </div>
      <!--body-->
      <div class="d-flex my-4">
        <!--image-->
        <div class="me-2">
          <img class="post-profile align-self-start mr-3 rounded-circle shadow-sm" src="{{ url_for('static', filename='profile_pics/' + current_user.profile_picture) }}" alt="Generic placeholder image">
        </div>
        <!--form-->
        <div class="w-100">
          <form action="" method="POST">
            {{ form.hidden_tag() }}   <!-- IMPORTANT FOR SECURITY -->

            <!-- TITLE -->
            {% if form.title.errors %}
              {{ form.title(class="form-control is-invalid rounded p-2 mb-2") }}
              <div class="invalid-feedback">
                {% for error in form.title.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.title(class="form-control rounded p-2 mb-2") }}
            {% endif %}


            <!-- CONTENT -->
            {% if form.content.errors %}
              {{ form.content(class="form-control is-invalid post rounded p-2 mb-4") }}
              <div class="invalid-feedback">
                {% for error in form.content.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.content(class="form-control post rounded p-2 mb-4") }}
            {% endif %}            


            <label>Select Tags:</label>
            <div class="input-group mb-2">
              {% if dropdown_error %}
                {{ form.topics(class="form-select is-invalid") }}
              	{{ form.add_topic(class="btn btn-light border") }}
                <div class="invalid-feedback">
                    <span>{{ dropdown_error }}</span>
                </div>
              {% else %}
                {{ form.topics(class="form-select") }}
              	{{ form.add_topic(class="btn btn-light border") }}
              {% endif %}

            </div>

            <div class="d-flex flex-wrap">
              {% for tag in tags %}
                  <input type=submit title="Click to remove tags" class="btn btn-sm btn-tags m-1" name="tag_to_remove" value="{{ tag }}">
              {% endfor %}
            </div>
            {#
            <div class="d-flex">
              <button type="button" class="btn btn-sm btn-post flex-fill">
                <i class="fas fa-newspaper icon-left"></i>
                Attach News Article
              </button>|
              <button type="button" class="btn btn-sm btn-post flex-fill">
                <i class="fas fa-images icon-left"></i>
                Add Image/Video
              </button>
            </div>
            #}
            {{ form.submit(class="btn btn-grad mb-1") }}
          </form>
        </div>
      </div>
    </div>

	</div>
{% endblock %}

news_curation/templates/post/post.html
{% extends "layout.html" %}

{% block style %}
  <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}Home{% endblock %}

{% block header_class %}
<!-- classname for small header -->
  header
{% endblock %}

{% block content %}
  <div class="content-container mx-auto p-5 shadow-sm">
  <article class="p-5 mb-4 rounded shadow-sm">
    <div class="media">
      <!--post header-->
      <div class="d-flex align-items-center">
        <div class="me-2">
          <img class="post-profile align-self-start mr-3 rounded-circle shadow-sm" src="{{ url_for('static', filename='profile_pics/' + post.author.profile_picture) }}" alt="Generic placeholder image">
        </div>
        <div>
          <h3 class="mt-0">{{ post.author.username }}</h3>
          <small>{{ post.created_at.strftime("%Y-%m-%d %H:%M") }}</small>
        </div>

        <!--dropdown menu-->
        <div class="dropdown ms-auto">
          <button class="btn btn-icon dropdown-toggle" type="button" id="dropdownMenu" data-bs-toggle="dropdown" data-bs-display="static" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenu">
            <!-- <a class="dropdown-item" type="button" href="{{ url_for('post.save_post', post_id=post.id, home='False') }}"><i class="fas fa-star icon-left me-2"></i>Save</a> -->
            
            <!-- save post -->
            {% if current_user not in post.saved_by %}
            <a class="dropdown-item" href="{{ url_for('post.save_post', post_id=post.id, home='False') }}"><i class="fas fa-star icon-left me-2"></i>Save</a>
            {% else %}
            <a class="dropdown-item text-primary" href="{{ url_for('post.remove_saved', post_id=post.id, home='False') }}"><i class="fas fa-star icon-left me-2"></i>Saved</a>
            {% endif %}

            <!-- update delete -->
            {% if post.author == current_user %}
            <a class="dropdown-item" href="{{ url_for('post.update_post', post_id=post.id) }}"><i class="fas fa-edit icon-left me-2"></i>Update</a>
            <button class="dropdown-item" type="button" data-bs-toggle="modal" data-bs-target="#deleteModal"><i class="fas fa-trash-alt icon-left me-2"></i>&nbsp;Delete</button>
            {% endif %}
          </div>
        </div>
      </div>
      <!--post content-->        
      <div class="media-body mt-3 text-break"> 
        <!--title-->
        <h5>{{ post.title }}</h5>
        <!--content-->
        <p>{{ post.content }}</p>
      </div>


      <!--post footer-->
      <div class="d-flex">
        <!--comment-->
        <div class="me-auto">
          <button type="button" class="btn btn-icon">
            <i class="fas fa-ellipsis-h icon-left"></i>
            <span>{{ post.comments|length if post.comments else '0'}} Comments</span>
          </button>
        </div>
        <!--rate-->
        <div>
          <a class="btn btn-icon me-2" href="{{ url_for('post.like_post', post_id=post.id, home='False') }}">
            {% if current_user not in post.liker %}
            <i class="fas fa-arrow-up icon-left"></i>
            <span>{{ post.liker|length }}</span>
            {% else %} <!-- if user likes -->
            <i class="fas fa-arrow-up icon-left text-primary"></i>
            <span class="text-primary">{{ post.liker|length }}</span>
            {% endif %}
          </a>
          <a class="btn btn-icon me-2" href="{{ url_for('post.dislike_post', post_id=post.id, home='False') }}">
            {% if current_user not in post.disliker %}
            <i class="fas fa-arrow-down icon-left"></i>
            <span>{{ post.disliker|length }}</span>
            {% else %} <!-- if user dislikes -->
            <i class="fas fa-arrow-down icon-left text-primary"></i>
            <span class="text-primary">{{ post.disliker|length }}</span>
            {% endif %}
          </a>
        </div>
      </div>

    </div>

    <!--comment section-->
    <div>

      <!--write a comment-->
      <div class="d-flex align-items-center">
        <div class="me-2">
          <img class="comment-profile align-self-start mr-3 rounded-circle shadow-sm" src="{{ url_for('static', filename='default.jpg') }}" alt="Generic placeholder image">
        </div>
        <div class="rounded my-4" style="width: 100%;">
          <a href="{{ url_for('comment.add',post_id=post.id) }}" class="btn-create-post border border-2 rounded p-2 d-block" style="width: 100%;">Tell us your thoughts...</a>
          
        </div>
      </div>

      
      {% for comment in post.comments %}
        <div class="media">
          <div class="mt-4 align-items-center">
            <div class="d-flex ">
              <div class="me-2">
                <img class="comment-profile align-self-start mr-3 rounded-circle shadow-sm" src="{{ url_for('static', filename='default.jpg') }}" alt="Generic placeholder image">
              </div>
              <div class="w-100">
                <h4 class="mt-0">{{ comment.author.first_name }} {{ comment.author.last_name}}</h4>
                <small>{{ comment.created_at }}</small>
                <!--comment content-->
                <div class="mt-2 text-break">
                  <p>{{ comment.content }}</p>
                </div>
                <div class="d-flex justify-content-end">
                </div>
              </div>
            </div>
            
            
          </div>
        </div>
      {% endfor %}

      

      </div>
      <!--end of sample comment-->

    </div>
  </article>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{{ url_for('post.delete_post', post_id=post.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input type="submit" class="btn btn-danger" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}