news_curation/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired, ValidationError
from news_curation.classifier.utils import predict

class PostForm(FlaskForm):
	title = StringField('Title', 
		validators=[DataRequired()], 
		render_kw={"placeholder": "Title"})
	content = TextAreaField('Content', 
		validators=[DataRequired()], 
		render_kw={"placeholder": "Tell us your thoughts..."})
	topics = SelectField('Topics', coerce=int, validators=[DataRequired()]) #dropdown options are defined in routes.py

	add_topic = SubmitField('Add Tag')
	submit = SubmitField('Post')

	# validate content using model

	def validate_content(self, content):
		if predict(content.data):
			raise ValidationError("Content is detected as fake.")

news_curation/post/__init__.py
from flask import Blueprint

bp = Blueprint("post", __name__)

from news_curation.post import routes, models

news_curation/post/routes.py
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import login_required, current_user

from news_curation.extensions import db

from news_curation.post import bp
from news_curation.post.models import Post

from news_curation.comment.forms import CommentForm

from news_curation.post.forms import PostForm
from news_curation.post.models import Post

from news_curation.topic.models import Topic, topics


@bp.route("/")
def home():
    return "post home"

# <<<<<<< HEAD
# @bp.route("/<int:post_id>", methods=["POST","GET"])
# @login_required
# def read(post_id):
#     post = Post.query.get_or_404(post_id)

#     form = CommentForm()

#     # if form.validate_on_submit():
#     #     pass

#     return post.content
# =======

tags = []
@bp.route("/create", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    form.topics.choices = [(g.id, g.topic) for g in Topic.query.order_by('topic')] #choices for the topic dropdown.
    dropdown_error = None
    if request.method == 'POST':
        if form.submit.data: #when user clicks the 'Post' button
            if not tags: #if there were no tags added
                dropdown_error = "Tags cannot be empty! Please add at least one."
                return render_template('post/manage_post.html', form=form, legend='New Post', 
                                        tags=tags, dropdown_error=dropdown_error)
            elif form.validate_on_submit():
                post = Post(title=form.title.data, content=form.content.data, author=current_user)
                db.session.add(post) #adds new post to database
                
                for tag in tags: #add selected tags to the post in the database
                    post_tag = Topic.query.filter_by(topic=tag).first()
                    post.topic.append(post_tag)

                db.session.commit()
                del tags[0:] #delete all content of the 'tags' list
                flash('Post has been created!', 'success')
                return redirect(url_for('user.home'))

        elif form.add_topic.data: #when user clicks the 'add topic' button
            #append name of selected choice to a list
            
            topic_name = dict(form.topics.choices).get(form.topics.data)
            try:
                tags.index(topic_name) #checks if a tag is already in the 'tags' list
            except:
                tags.append(topic_name) #appends the selected tag to 'tags' if it is not yet in the list
            else:
                dropdown_error = "This tag has already been added!"
            return render_template('post/manage_post.html', form=form, legend='New Post', 
                                        tags=tags, dropdown_error=dropdown_error)

        elif request.form['tag_to_remove']: #when one of the added tags is clicked (this will remove that tag)
            tag_name = request.form.get('tag_to_remove')
            tags.remove(tag_name)
            return render_template('post/manage_post.html', form=form, legend='New Post', tags=tags)
    
    del tags[0:]
    return render_template('post/manage_post.html', form=form, legend='New Post')


#viewing a single post
@bp.route("/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post/post.html', post=post)

tags_to_remove = []
@bp.route("<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    # tags = []
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: #if logged-in user is not the author of post, abort
        abort(403)

    form = PostForm()
    form.topics.choices = [(g.id, g.topic) for g in Topic.query.order_by('topic')] #choices for the topic dropdown.
    dropdown_error = None

    if request.method == 'POST':
        if form.submit.data and form.validate_on_submit(): #updates the post
            if not tags: #if there were no tags added
                dropdown_error = "Tags cannot be empty! Please add at least one."
                return render_template('post/manage_post.html', form=form, legend='Update Post', 
                                        tags=tags, dropdown_error=dropdown_error)
            post.title = form.title.data
            post.content = form.content.data
            for tag in tags_to_remove:
                tag_row = Topic.query.filter_by(topic=tag).first() #gets the row of selected tag in Topic table
                if tag_row in post.topic:
                    post.topic.remove(tag_row)

            for tag in tags: #add selected tags to the post in the database
                tag_row = Topic.query.filter_by(topic=tag).first() #gets the row of selected tag in Topic table
                #if selected tag is not yet associated to the post
                if tag_row not in post.topic: #prevents duplicate rows in topics table
                    post.topic.append(tag_row)
            
            db.session.commit()
            del tags[0:] #delete all content of the 'tags' list
            del tags_to_remove[0:]
            flash('Post has been updated!', 'success')
            return redirect(url_for('post.post', post_id=post.id))

        elif form.add_topic.data: #when user clicks the 'add topic' button
            #append name of selected choice to a list
            topic_name = dict(form.topics.choices).get(form.topics.data)
            try:
                tags.index(topic_name) #checks if a tag is already in the 'tags' list
            except:
                tags.append(topic_name) #appends the selected tag to 'tags' if it is not yet in the list
            else:
                dropdown_error = "This tag has already been added!"
                return render_template('post/manage_post.html', form=form, legend='Update Post',
                                        tags=tags, dropdown_error=dropdown_error)

        elif request.form['tag_to_remove']: #when one of the added tags is clicked (this will remove that tag)
            tag_name = request.form.get('tag_to_remove')
            tags_to_remove.append(tag_name)
            tags.remove(tag_name)

    elif request.method == 'GET': #displays the data of the post when page is opened
        form.title.data = post.title
        form.content.data = post.content
        del tags[0:]
        for topic in post.topic:   
            tags.append(topic.topic)

    return render_template('post/manage_post.html', title='Update Post', form=form, legend='Update Post', tags=tags)


@bp.route("/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted!', 'success')
    return redirect(url_for('user.profile'))


# Saving post
@bp.route("/<int:post_id>/save")
@login_required
def save_post(post_id):
	home = request.args.get('home')
	post = Post.query.get_or_404(post_id)

	if current_user in post.saved_by:	# if user has already saved the post
	    flash('Post is already in Saved Posts', 'info')
	else:
	    post.saved_by.append(current_user)
	    db.session.commit()
	    flash('Post has been saved!', 'success')

	if home == 'True': #return to homepage if saved from there
		return redirect(url_for('user.home', _anchor=post_id))
	elif home == 'Profile':
		return redirect(url_for('user.profile', _anchor=post_id))
	elif home == 'Popular':
		return redirect(url_for('user.popular', _anchor=post_id))
	else:
		return redirect(url_for('post.post', post_id=post_id))


# Removing saved post
@bp.route("/<int:post_id>/remove_saved")
@login_required
def remove_saved(post_id):
	home = request.args.get('home')

	post = Post.query.get_or_404(post_id)
	post.saved_by.remove(current_user)
	db.session.commit()
	flash('Post removed from Saved Posts', 'info')

	if home == 'True': #return to homepage if saved from there
		return redirect(url_for('user.home', _anchor=post_id))
	elif home == 'Saves':
		return redirect(url_for('user.saved_posts'))
	elif home == 'Profile':
		return redirect(url_for('user.profile', _anchor=post_id))
	elif home == 'Popular':
		return redirect(url_for('user.popular', _anchor=post_id))
	else:
		return redirect(url_for('post.post', post_id=post_id))


#Liking post
@bp.route("/<int:post_id>/like")
@login_required
def like_post(post_id):
	home = request.args.get('home')

	post = Post.query.get_or_404(post_id)
	# post.likes += 1
	# db.session.commit()

	if current_user not in post.liker:
		post.liker.append(current_user)
		if current_user in post.disliker: #if current user dislikes the post, remove dislike
			post.disliker.remove(current_user)
	else:
		post.liker.remove(current_user)
	
	db.session.commit()

	if home == 'True': #return to homepage if liked from there
		return redirect(url_for('user.home', _anchor=post_id))
	elif home == 'Saves':
		return redirect(url_for('user.saved_posts', _anchor=post_id))
	elif home == 'Profile':
		return redirect(url_for('user.profile', _anchor=post_id))
	elif home == 'Popular':
		return redirect(url_for('user.popular', _anchor=post_id))
	else:
		return redirect(url_for('post.post', post_id=post_id))

#Disliking post
@bp.route("/<int:post_id>/dislike")
@login_required
def dislike_post(post_id):
	home = request.args.get('home')

	post = Post.query.get_or_404(post_id)

	if current_user not in post.disliker: #if user is first time disliker, add to db
		post.disliker.append(current_user)
		if current_user in post.liker: #if current user likes the post, remove like
			post.liker.remove(current_user)
	else:
		post.disliker.remove(current_user)
	
	db.session.commit()

	if home == 'True': #return to homepage if disliked from there
		return redirect(url_for('user.home', _anchor=post_id))
	elif home == 'Saves':
		return redirect(url_for('user.saved_posts', _anchor=post_id))
	elif home == 'Profile':

news_curation/user/__init__.py
from flask import Blueprint

bp = Blueprint("user", __name__)

from news_curation.user import routes, models

news_curation/user/routes.py
#imports for profile picture
import os
import secrets  #for creating random hex for picture filename
from PIL import Image  #from Pillow package
#####

from flask import render_template, url_for, flash, redirect, request, current_app
from flask_login import current_user, login_user, logout_user, login_required
from sqlalchemy import desc, func

from news_curation.extensions import bcrypt, db

from news_curation.user import bp
from news_curation.user.forms import LoginForm, RegistrationForm, UpdateProfileForm
from news_curation.user.models import User, user_interests, likes

from news_curation.post.models import Post
from news_curation.topic.models import Topic, topics

@bp.route("/home")
def home():

    # can be also done using only one if and return

    if current_user.is_authenticated: #posts are only filtered for logged-in users; anonymouse users see all posts
        # join all tables then filter posts by the interests of current user
        user = User.query.filter_by(id=current_user.id).first()
        
        # for checking if a user has selected topics of interest
        ctr = 0
        for interest in user.topics_of_interest:
            ctr += 1
        
        if ctr >= 1:
            posts = Post.query.join(topics, Post.id == topics.c.post_id).join(user_interests, topics.c.topic_id == user_interests.c.topic_id).filter_by(user_id=current_user.id).order_by(desc(Post.created_at))
        else:
            posts = Post.query.order_by(desc(Post.created_at)).all()
    else:
        posts = Post.query.order_by(desc(Post.created_at)).all()
    
    return render_template('user/home.html', posts=posts, destination='True')

# sort by most popular
@bp.route("/popular")
def popular():
    posts = Post.query.outerjoin(likes, Post.id == likes.c.post_id).group_by(Post.id).order_by(desc(func.count(likes.c.user_id))).all()
    return render_template('user/home.html', posts=posts, destination='Popular')


@bp.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:   #prevents logged-in user from going to register page
        return redirect(url_for('user.home'))

    form = RegistrationForm()

    if form.validate_on_submit():
        #generate hashed password for the password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        
        user = User(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                username=form.username.data,
                email=form.email.data,
                password=hashed_password
            )
        db.session.add(user)
        db.session.commit()

        flash('Your account has been created!', 'success')
        return redirect(url_for('user.login'))

    return render_template('user/register.html', form=form)



@bp.route("/login", methods=['GET', 'POST'])
def login():
    
    #prevents logged-in user from going to login page
    if current_user.is_authenticated:
        flash('You are already logged in.', 'success')
        return redirect(url_for('user.home'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            #when logged-out users access restricted pages, they will be redirected
            #to login. After logging in, they will be redirected to the page they wanted to access(next_page)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('user.home'))
        
        else:
            flash('Login Unsuccessful. Please check your username and password.', 'danger')

    return render_template('user/login.html', form=form)

@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('user.home'))


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_picture.filename) #split the picture's filename and extension
    picture_fn = random_hex + f_ext #this will be the filename of picture when saved    
    picture_path = os.path.join(current_app.root_path, 'static/profile_pics', picture_fn)
    
    output_size = (500, 500)
    i = Image.open(form_picture)
    i.thumbnail(output_size)

    i.save(picture_path)

    return picture_fn

@bp.route("/profile", methods=['GET', 'POST'])
@login_required     #prevents anonymous user from going to profile page
def profile():
    # user_posts = Post.query.filter_by(user_id=current_user.id).all()
    user_posts = Post.query.filter_by(user_id=current_user.id).order_by(desc(Post.created_at)).all() #order by latest first
    form = UpdateProfileForm()
    error = False
        
    if form.validate_on_submit():
        if form.picture.data:   #if a picture was uploaded
            picture_file = save_picture(form.picture.data)
            current_user.profile_picture = picture_file     #save the picture file to database
        if form.password.data:
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            current_user.password = hashed_password

        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Profile successfully updated!', 'success')
        return redirect(url_for('user.profile'))
    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.username.data = current_user.username
        form.email.data = current_user.email
    else:
        error = True

    image_file = url_for('static', filename='profile_pics/' + current_user.profile_picture)
    return render_template('user/profile.html', user_posts=user_posts, 
                            form=form, error=error, image_file=image_file)

#View saved posts
@bp.route("/saved_posts")
@login_required
def saved_posts():
    posts = current_user.saved_posts.order_by(desc(Post.created_at)).all()

    return render_template('user/saved_posts.html', posts=posts)

news_curation/templates/user/create-post.html
{% extends "layout.html" %}

{% block style %}
	<link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}Home{% endblock %}

{% block header_class %}
<!-- classname for small header -->
	header
{% endblock %}

{% block content %}
	<div class="content-container mx-auto p-5 shadow-sm">

    <!--create post-->
    <div class="media px-5 py-2 my-4 rounded shadow-sm">
      <!--header-->
      <div>
        <h4 class="text-center w-100">Create Post</h4>
      </div>
      <!--body-->
      <div class="d-flex my-4">
        <!--image-->
        <div class="me-2">
          <img class="post-profile align-self-start mr-3 rounded-circle shadow-sm" src="images/seulgi.jpg" alt="Generic placeholder image">
        </div>
        <!--form-->
        <div class="w-100">
          <form>
            <input type="text" class="form-control rounded p-2 mb-2" placeholder="Title"/>
            <textarea class="form-control post rounded p-2 mb-4" placeholder="Tell us your thoughts..."></textarea>
            <label>Select Tags:</label>
            <div class="input-group mb-2">
              <select class="form-select" aria-label="Default select example">
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
              </select>
              <button class="btn btn-light border" type="button">Add Topic</button>
            </div>
            <div class="d-flex flex-wrap">
              <input type="submit" class="btn btn-sm btn-secondary m-1" name="tag_to_remove" value="sample tag">
            </div>
            <div class="d-flex">
              <button type="button" class="btn btn-sm btn-post flex-fill">
                <i class="fas fa-newspaper icon-left"></i>
                Attach News Article
              </button>|
              <button type="button" class="btn btn-sm btn-post flex-fill">
                <i class="fas fa-images icon-left"></i>
                Add Image/Video
              </button>
            </div>
            <button type="button" name="button" class="btn btn-grad mb-1">Post</button>
          </form>
        </div>
      </div>
    </div>

	</div>
{% endblock %}

news_curation/templates/user/home.html
{% extends "layout.html" %}

{% block style %}
	<link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}Home{% endblock %}

{% block header_class %}
<!-- classname for small header -->
	header
{% endblock %}
{% block content %}
	<div class="content-container mx-auto p-5 shadow-sm">
    <!--create post-->
    <div class="media px-5 py-3 mb-4 rounded shadow-sm">
      <div class="d-flex align-items-center">
        <!--image-->
        <div class="me-2">
          {% if current_user.is_authenticated %}
          <img class="post-profile align-self-start mr-3 rounded-circle shadow-sm" src="{{ url_for('static', filename='profile_pics/' + current_user.profile_picture) }}" alt="Generic placeholder image">
          {% else %}
          <img class="post-profile align-self-start mr-3 rounded-circle shadow-sm" src="{{ url_for('static', filename='profile_pics/default.jpg') }}" alt="Generic placeholder image">
          {% endif %}
        </div>
        <!--post bar-->
        <form action="{{ url_for('post.new_post') }}" class="w-100">
          <div class="my-4">
            <input type="submit" class="btn-create-post border border-2 rounded p-2" value="Create Post"/>
          </div>
        </form>    
      </div>  
    </div>


<!-- sort posts -->
    <div class="media px-5 py-3 mb-4 rounded shadow-sm">
      {% if destination == 'True' %}
      <a href="{{ url_for('user.home') }}" class="btn btn-primary">All Posts</a>
      <a href="{{ url_for('user.popular') }}" class="btn btn-secondary">Most Popular</a>
      {% else %}
      <a href="{{ url_for('user.home') }}" class="btn btn-secondary">All Posts</a>
      <a href="{{ url_for('user.popular') }}" class="btn btn-primary">Most Popular</a>
      {% endif %}
    </div>

	{% for post in posts %}
		<article id="{{ post.id }}" class="media content-section p-5 mb-4 rounded shadow-sm">
        <!--user image and name-->
        <div class="d-flex align-items-center">
          <!--image-->
          <div class="me-2">
            <img class="post-profile align-self-start mr-3 rounded-circle shadow-sm" src="{{ url_for('static', filename='profile_pics/' + post.author.profile_picture) }}" alt="Generic placeholder image">
          </div>
          <!--name and date-->
          <div>
            <h3 class="mt-0">{{ post.author.username }}</h3>
            <small>{{ post.created_at.strftime("%Y-%m-%d %H:%M") }}</small>
          </div>
          <!--save-->
          <div class="ms-auto">
              {% if current_user not in post.saved_by %}
              <a class="btn btn-icon" href="{{ url_for('post.save_post', post_id=post.id, home=destination) }}">
              <i class="fas fa-star icon-left"></i>
              <span>Save</span>
              {% else %}
              <a class="btn btn-icon" href="{{ url_for('post.remove_saved', post_id=post.id, home=destination) }}">
              <i class="fas fa-star icon-left text-primary"></i>
              <span class="text-primary">Saved</span>
              {% endif %}
            </a>
          </div>
        </div>
        <!--end of user image and name-->

      <a href="{{ url_for('post.post', post_id=post.id) }}">
      <!--article content-->        
        <div class="media-body mt-3 text-break"> 
          <!--title-->
          <h5>{{ post.title }}</h5>
          <!--content-->
          <p>{{ post.content }}</p>
        </div>
      <!--end of article content-->

      <!------ for printing the tags of the post --------->
      {% for topics in post.topic %}
      <button class="btn btn-sm btn-light mb-1" disabled>{{ topics.topic }}</button>
      {% endfor %}


        <!--comment and rate-->
        <div class="d-flex mt-2">
          <!--comment-->
          <div class="me-auto">
            <button type="button" class="btn btn-icon">
              <i class="fas fa-ellipsis-h icon-left"></i>
              <span>{{ post.comments|length if post.comments else '0'}} Comments</span>
            </button>
          </div>
      </a>
          <!--rate-->
          <div class="ms-auto">
            <a class="btn btn-icon me-2" href="{{ url_for('post.like_post', post_id=post.id, home=destination) }}">
              {% if current_user not in post.liker %}
              <i class="fas fa-arrow-up icon-left"></i>
              <span>{{ post.liker|length }}</span>
              {% else %} <!-- if user likes -->
              <i class="fas fa-arrow-up icon-left text-primary"></i>
              <span class="text-primary">{{ post.liker|length }}</span>
              {% endif %}
            </a>
            <a class="btn btn-icon me-2" href="{{ url_for('post.dislike_post', post_id=post.id, home=destination) }}">
              {% if current_user not in post.disliker %}
              <i class="fas fa-arrow-down icon-left"></i>
              <span>{{ post.disliker|length }}</span>
              {% else %} <!-- if user dislikes -->
              <i class="fas fa-arrow-down icon-left text-primary"></i>
              <span class="text-primary">{{ post.disliker|length }}</span>
              {% endif %}
            </a>
          </div>
        </div>
        <!--end of comment and rate-->
		</article>
	{% endfor %}
	</div>
{% endblock %}

news_curation/templates/user/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock %}

{% block content %}
	<!-- Contents -->
	<div class="login-container shadow-sm">
	    <h1 class="text-center">Welcome!</h1>
	    <p class="title text-center">Please log in to continue</p>
	    <div class="input-container mt-4">
	    	<!-- ST: added id to form for testing -->
	        <form id="loginForm" action="" method="POST">
	        	{{ form.hidden_tag() }} 	<!-- IMPORTANT FOR SECURITY -->
	        	<fieldset class="form-group">
	        		<!-- USERNAME -->
		            <div class="input-group mb-3">
		                <span class="input-group-text"><i class="fas fa-user"></i></span>
		                <!-- displaying error for invalid input -->
						{% if form.username.errors %}
							{{ form.username(class="form-control is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.username.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.username(class="form-control input-field", placeholder="Username") }}
						{% endif %}
						<!-- displaying error for invalid input -->
		                <br>
		            </div>
		            <!-- PASSWORD -->
		            <div class="input-group mb-2">
		                <span class="input-group-text"><i class="fas fa-key"></i></span>
		                <!-- displaying error for invalid input -->
						{% if form.password.errors %}
							{{ form.password(class="form-control is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.password.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.password(class="form-control input-field", placeholder="Password") }}
						{% endif %}
						<!-- displaying error for invalid input -->
		            </div>
		            <div class="form-check mb-4">
			        	{{ form.remember(class="form-check-input") }}
			        	{{ form.remember.label(class="form-check-label") }}
		            </div>
	        	</fieldset>

	        	<div class="form-group mb-4">
					{{ form.submit(class="btn btn-grad") }}
	            </div>
	        </form>
	    </div>
	    
	    <div>
	        <div class="d-flex justify-content-center">
	            <small>Don't have an account?&nbsp</small><a class="highlight" href="{{ url_for('user.register') }}" class="ml-2">Sign Up</a>
	        </div>

	    </div>
	</div>
{% endblock %}

news_curation/templates/user/read.html
"""Read users"""

news_curation/templates/user/register.html
{% extends "layout.html" %}

{% block title %}Register{% endblock %}

{% block content %}
    {% meld "registration_form" %}
{% endblock %}

news_curation/templates/user/saved_posts.html
{% extends "layout.html" %}

{% block style %}
	<link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}Home{% endblock %}

{% block header_class %}
<!-- classname for small header -->
	header
{% endblock %}
{% block content %}
	<div class="content-container mx-auto p-5 shadow-sm">

  {% if not posts %}
    <br>
    <p>You have not saved any posts. Visit your feed and save some!</p>
  {% else %}
  	{% for post in posts %}
  		<article id="{{ post.id }}" class="media content-section p-5 mb-4 rounded shadow-sm">
          <!--user image and name-->
          <div class="d-flex align-items-center">
            <!--image-->
            <div class="me-2">
              <img class="post-profile align-self-start mr-3 rounded-circle shadow-sm" src="{{ url_for('static', filename='profile_pics/' + post.author.profile_picture) }}" alt="Generic placeholder image">
            </div>
            <!--name and date-->
            <div>
              <h3 class="mt-0">{{ post.author.username }}</h3>
              <small>{{ post.created_at.strftime("%Y-%m-%d %H:%M") }}</small>
            </div>
            <!--save-->
            <div class="ms-auto">
              <a class="btn btn-icon" href="{{ url_for('post.remove_saved', post_id=post.id, home='Saves') }}">
                <i class="fas fa-times icon-left"></i>
                <span>Remove</span>
              </a>
            </div>
          </div>
          <!--end of user image and name-->

      <a href="{{ url_for('post.post', post_id=post.id) }}">
      <!--article content-->        
        <div class="media-body mt-3 text-break"> 
          <!--title-->
          <h5>{{ post.title }}</h5>
          <!--content-->
          <p>{{ post.content }}</p>
        </div>
      <!--end of article content-->

      <!------ for printing the tags of the post --------->
      {% for topics in post.topic %}
      <button class="btn btn-sm btn-light mb-1" disabled>{{ topics.topic }}</button>
      {% endfor %}


        <!--comment and rate-->
        <div class="d-flex">
          <!--comment-->
          <div class="me-auto">
            <button type="button" class="btn btn-icon">
              <i class="fas fa-ellipsis-h icon-left"></i>
              <span>{{ post.comments|length if post.comments else '0'}} Comments</span>
            </button>
          </div>
          <!--rate-->
          <div class="ms-auto">
            <a class="btn btn-icon me-2" href="{{ url_for('post.like_post', post_id=post.id, home='Saves') }}">
            {% if current_user not in post.liker %}
            <i class="fas fa-arrow-up icon-left"></i>
            <span>{{ post.liker|length }}</span>
            {% else %} <!-- if user likes -->
            <i class="fas fa-arrow-up icon-left text-primary"></i>
            <span class="text-primary">{{ post.liker|length }}</span>
            {% endif %}
            </a>
            <a class="btn btn-icon me-2" href="{{ url_for('post.dislike_post', post_id=post.id, home='Saves') }}">
              {% if current_user not in post.disliker %}
              <i class="fas fa-arrow-down icon-left"></i>
              <span>{{ post.disliker|length }}</span>
              {% else %} <!-- if user dislikes -->
              <i class="fas fa-arrow-down icon-left text-primary"></i>
              <span class="text-primary">{{ post.disliker|length }}</span>
              {% endif %}
              </a>
            </div>
          </div>
          <!--end of comment and rate-->
        </a>
  		</article>
  	{% endfor %}
  {% endif %}
	</div>
{% endblock %}